name: build

on:
  push:
      paths-ignore:
        - '**/*.md'
        - '.gitignore'
        - '.dependabot/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          ignore: DL3059 DL3018 DL3007 DL3003

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.17
      - name: test
        run: |
          cd tests
          pip install --upgrade pip pipenv
          pipenv sync --dev
          pipenv run pytest -v

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: build dependencies
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: docker hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build
        run: |
          docker buildx build \
            --push \
            --tag robertbeal/flickrmirrorer:latest \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 .